# Generated by Django 5.2.8 on 2025-11-14 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockExchange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Stock exchange',
                'verbose_name_plural': 'Stock exchanges',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD'), ('EUR', 'EUR'), ('BRL', 'BRL'), ('OTHER', 'Other')], default='USD', help_text='Currency quoted against ARS (e.g. USD/ARS).', max_length=8)),
                ('official', models.DecimalField(decimal_places=6, max_digits=18)),
                ('mep', models.DecimalField(decimal_places=6, max_digits=18)),
                ('blue', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                'verbose_name': 'Exchange rate snapshot',
                'verbose_name_plural': 'Exchange rate snapshots',
                'ordering': ['-timestamp'],
                'unique_together': {('timestamp', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='StockInstrument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('yahoo_symbol', models.CharField(blank=True, help_text='Override for Yahoo Finance symbol (e.g., YPFD.BA).', max_length=32)),
                ('google_symbol', models.CharField(blank=True, help_text='Override for Google Finance symbol (e.g., YPFD:BCBA).', max_length=32)),
                ('instrument_type', models.CharField(choices=[('STOCK', 'Stock'), ('BOND', 'Bond'), ('ADR', 'ADR'), ('CEDEAR', 'CEDEAR'), ('ETF', 'ETF'), ('OTHER', 'Other')], default='STOCK', max_length=16)),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD'), ('EUR', 'EUR'), ('BRL', 'BRL'), ('OTHER', 'Other')], default='ARS', max_length=8)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='stock.stockexchange')),
            ],
            options={
                'verbose_name': 'Stock instrument',
                'verbose_name_plural': 'Stock instruments',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockOperation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('operation_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('price', models.BigIntegerField(help_text='Price per unit expressed in minor currency units (e.g. cents).')),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD'), ('EUR', 'EUR'), ('BRL', 'BRL'), ('OTHER', 'Other')], default='ARS', max_length=8)),
                ('fees', models.BigIntegerField(default=0, help_text='Total fees in minor units (e.g. cents).')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='stock.stockinstrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock operation',
                'verbose_name_plural': 'Stock operations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockInstrumentSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('as_of', models.DateTimeField(help_text='Timestamp provided by the upstream market data API.')),
                ('price', models.DecimalField(decimal_places=6, help_text='Most recent trade price expressed in major currency units.', max_digits=20)),
                ('open_price', models.DecimalField(blank=True, decimal_places=6, help_text='Opening price for the current session.', max_digits=20, null=True)),
                ('day_high', models.DecimalField(blank=True, decimal_places=6, help_text='Session high price.', max_digits=20, null=True)),
                ('day_low', models.DecimalField(blank=True, decimal_places=6, help_text='Session low price.', max_digits=20, null=True)),
                ('volume', models.BigIntegerField(blank=True, help_text='Latest reported traded volume in units/shares.', null=True)),
                ('data_source', models.CharField(blank=True, help_text='Identifier for the API or data feed that produced the snapshot.', max_length=64)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='stock.stockinstrument')),
            ],
            options={
                'verbose_name': 'Stock instrument snapshot',
                'verbose_name_plural': 'Stock instrument snapshots',
                'ordering': ['instrument'],
                'constraints': [models.UniqueConstraint(fields=('instrument',), name='stock_single_snapshot_per_instrument')],
            },
        ),
    ]
