# Generated by Django 5.2.8 on 2025-11-12 01:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInstrument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('instrument_type', models.CharField(choices=[('STOCK', 'Stock'), ('BOND', 'Bond'), ('ADR', 'ADR'), ('CEDEAR', 'CEDEAR'), ('ETF', 'ETF'), ('OTHER', 'Other')], default='STOCK', max_length=16)),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD'), ('EUR', 'EUR'), ('BRL', 'BRL'), ('OTHER', 'Other')], default='ARS', max_length=8)),
                ('exchange', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Stock instrument',
                'verbose_name_plural': 'Stock instruments',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD'), ('EUR', 'EUR'), ('BRL', 'BRL'), ('OTHER', 'Other')], default='USD', help_text='Currency quoted against ARS (e.g. USD/ARS).', max_length=8)),
                ('official', models.DecimalField(decimal_places=6, max_digits=18)),
                ('mep', models.DecimalField(decimal_places=6, max_digits=18)),
                ('blue', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                'verbose_name': 'Exchange rate snapshot',
                'verbose_name_plural': 'Exchange rate snapshots',
                'ordering': ['-timestamp'],
                'unique_together': {('timestamp', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='StockOperation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('operation_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('price', models.BigIntegerField(help_text='Price per unit expressed in minor currency units (e.g. cents).')),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD'), ('EUR', 'EUR'), ('BRL', 'BRL'), ('OTHER', 'Other')], default='ARS', max_length=8)),
                ('fees', models.BigIntegerField(default=0, help_text='Total fees in minor units (e.g. cents).')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='stock.stockinstrument')),
            ],
            options={
                'verbose_name': 'Stock operation',
                'verbose_name_plural': 'Stock operations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
